name: Prepare Node
description: 'Prepares the Node environment for the repository'

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '22'

    - uses: yarnpkg/setup-action@main

    - name: Install dependencies
      shell: bash
      run: |
        yarn install
