compressionLevel: 9

packageExtensions:
  "@astrojs/preact@*":
    peerDependencies:
      "@babel/core": "*"
  "@astrojs/starlight-docsearch@*":
    peerDependencies:
      "astro": "*"
  "starlight-auto-sidebar@*":
    peerDependencies:
      "astro": "*"
