use std::{process::{Command, Output}, str::FromStr};

use itertools::Itertools;
use zpm_git::PrepareParams;
use zpm_primitives::Locator;
use zpm_utils::{Path, ToFileString, to_shell_line};

use crate::{
    error::Error,
    script::ScriptEnvironment,
};

pub mod python;

#[derive(Debug)]
enum PackageManager {
    Npm,
    Pnpm,

    // Admittedly we perhaps change the `yarn pack` interface a little too often
    YarnClassic,
    YarnModern,
    YarnZpm,
}

pub async fn prepare_project(_locator: &Locator, folder_path: &Path, params: &PrepareParams) -> Result<Vec<u8>, Error> {
    let package_manager
        = get_package_manager(folder_path)?;

    match package_manager {
        PackageManager::Npm
            => prepare_npm_project(folder_path, params).await,

        PackageManager::Pnpm
            => prepare_pnpm_project(folder_path, params).await,

        PackageManager::YarnClassic
            => prepare_yarn_classic_project(folder_path, params).await,

        PackageManager::YarnModern
            => prepare_yarn_modern_project(folder_path, params).await,

        PackageManager::YarnZpm
            => prepare_yarn_zpm_project(folder_path, params).await,
    }
}

async fn run_prepared_command<I, S>(
    mut command: Command,
    folder_path: &Path,
    args: I,
    env: impl IntoIterator<Item = (&'static str, String)>,
    delete_env: impl IntoIterator<Item = &'static str>,
) -> Result<Output, Error>
where
    I: IntoIterator<Item = S>,
    S: AsRef<str>,
{
    command.current_dir(folder_path.to_path_buf());
    command.args(args.into_iter().map(|arg| arg.as_ref().to_string()));

    for key in ["CACHE_CWD", "INIT_CWD", "NODE_OPTIONS", "PROJECT_CWD", "npm_config_user_agent", "npm_execpath"] {
        command.env_remove(key);
    }

    for (key, value) in env {
        command.env(key, value);
    }

    for key in delete_env {
        command.env_remove(key);
    }

    let program = command.get_program().to_string_lossy().to_string();
    let shell_line = to_shell_line(&command).unwrap_or_else(|_| program.clone());

    let output = tokio::task::spawn_blocking(move || command.output()).await??;

    if output.status.success() {
        return Ok(output);
    }

    if let Ok(temp_dir) = Path::temp_dir() {
        let log_path = temp_dir
            .with_join_str("error.log");

        let stdout
            = String::from_utf8_lossy(&output.stdout);
        let stderr
            = String::from_utf8_lossy(&output.stderr);

        let log_write = log_path
            .fs_write_text(format!("=== COMMAND ===\n\n{}\n\n=== STDOUT ===\n\n{}\n=== STDERR ===\n\n{}", shell_line, stdout, stderr));

        if log_write.is_ok() {
            return Err(Error::ChildProcessFailedWithLog(program, log_path));
        }
    }

    Err(Error::ChildProcessFailed(program))
}

async fn make_yarn_command(release_line: zpm_switch::ReleaseLine) -> Result<Command, Error> {
    let channel_selector
        = release_line.stable();

    let version
        = zpm_switch::resolve_channel_selector(&channel_selector)
            .await?;

    Ok(zpm_switch::install_package_manager(&zpm_switch::VersionPackageManagerReference {version}).await?)
}

fn get_package_manager(folder_path: &Path) -> Result<PackageManager, Error> {
    let yarn_lock_path = folder_path
        .with_join_str("yarn.lock")
        .fs_read_text();

    if let Ok(yarn_lock) = yarn_lock_path {
        if yarn_lock.starts_with("{") {
            return Ok(PackageManager::YarnZpm);
        } else if yarn_lock.starts_with("# This file is generated by running \"yarn install\" inside your project.") {
            return Ok(PackageManager::YarnModern);
        } else {
            return Ok(PackageManager::YarnClassic);
        }
    } else if let Err(err) = yarn_lock_path {
        if err.io_kind() != Some(std::io::ErrorKind::NotFound) {
            return Err(err.into());
        }
    }

    if folder_path.with_join_str("pnpm-lock.yaml").fs_exists() {
        return Ok(PackageManager::Pnpm);
    }

    if folder_path.with_join_str("package-lock.json").fs_exists() {
        return Ok(PackageManager::Npm);
    }

    Ok(PackageManager::YarnZpm)
}

async fn prepare_npm_project(folder_path: &Path, params: &PrepareParams) -> Result<Vec<u8>, Error> {
    if params.workspace.is_some() {
        // We run "npm version" and check it returns >=7.x

        let version_result = ScriptEnvironment::new()?
            .with_cwd(folder_path.clone())
            .run_exec("npm", vec!["--version"])
            .await?
            .ok()?;

        let version_stdout
            = String::from_utf8(version_result.output().stdout.trim_ascii().to_vec())?;

        let version
            = zpm_semver::Version::from_str(&version_stdout)
               .expect("Expected a valid version");

        if version.major < 7 {
            return Err(Error::UnsupportedNpmWorkspaces(version));
        }
    }

    ScriptEnvironment::new()?
        .with_cwd(folder_path.clone())

        // Otherwise npm won't properly set the user agent, using the Yarn one instead
        .delete_env_variable("npm_config_user_agent")

        // Remove environment variables that limit the install to just production dependencies
        .delete_env_variable("npm_config_production")
        .delete_env_variable("NPM_CONFIG_PRODUCTION")
        .delete_env_variable("NODE_ENV")

        // We can't use `npm ci` because some projects don't have npm
        // lockfiles that are up-to-date. Hopefully npm won't decide
        // to change the versions randomly.
        .run_exec("npm", vec!["install", "--legacy-peer-deps"])
        .await?
        .ok()?;

    let pack_args = match &params.workspace {
        Some(workspace) => vec!["pack", "--silent", "--workspace", workspace],
        None => vec!["pack", "--silent"],
    };

    let pack_result = ScriptEnvironment::new()?
        .with_cwd(folder_path.clone())

        // Otherwise npm won't properly set the user agent, using the Yarn one instead
        .delete_env_variable("npm_config_user_agent")

        .run_exec("npm", pack_args)
        .await?
        .ok()?;

    let stdout
        = &pack_result.output().stdout;

    // We retrieve the last line of the output; it's the name of the pack file
    let first_char_index = stdout.iter()
        .enumerate()
        .rev()
        .skip(1)
        .find_position(|(_, c)| **c == b'\n')
        .map(|(_, (i, _))| i + 1)
        .unwrap_or(0);

    let last_line
        = &stdout[first_char_index..stdout.len() - 1];

    let pack_file
        = String::from_utf8(last_line.to_vec())?;

    let pack_tgz = folder_path
        .with_join_str(pack_file)
        .fs_read()?;

    Ok(pack_tgz)
}

async fn prepare_yarn_classic_project(folder_path: &Path, params: &PrepareParams) -> Result<Vec<u8>, Error> {
    // Otherwise Yarn 1 will pack the .yarn directory :(
    folder_path
        .with_join_str(".npmignore")
        .fs_append("/.yarn\n")?;

    run_prepared_command(
        make_yarn_command(zpm_switch::ReleaseLine::Classic).await?,
        folder_path,
        ["install"],
        [],
        ["NODE_ENV"],
    ).await?;

    let pack_path = folder_path
        .with_join_str("package.tgz");

    let pack_args = match &params.workspace {
        Some(workspace) => vec!["workspace", workspace.as_str(), "pack", "--filename", pack_path.as_str()],
        None => vec!["pack", "--filename", pack_path.as_str()],
    };

    run_prepared_command(
        make_yarn_command(zpm_switch::ReleaseLine::Classic).await?,
        folder_path,
        pack_args,
        [],
        [],
    ).await?;

    let pack_tgz
        = pack_path.fs_read()?;

    Ok(pack_tgz)
}

async fn prepare_yarn_modern_project(folder_path: &Path, params: &PrepareParams) -> Result<Vec<u8>, Error> {
    // If a lockfile doesn't exist we create a empty one to
    // prevent the project root detection from thinking it's in an
    // undeclared workspace when the user has a lockfile in their home
    // directory on Windows
    let lockfile_path = folder_path
        .with_join_str("yarn.lock");

    if !lockfile_path.fs_exists() {
        lockfile_path.fs_write(b"")?;
    }

    let mut pack_args
        = vec![];

    if let Some(workspace) = &params.workspace {
        pack_args.push("workspace");
        pack_args.push(workspace.as_str());
    }

    pack_args.push("pack");
    pack_args.push("--install-if-needed");

    let pack_path = folder_path
        .with_join_str("package.tgz");

    // TODO: Remove that hack once the clipanion-rs public repository
    // is migrated to Yarn 6.
    if let Some(workspace) = &params.workspace {
        if workspace.starts_with("@clipanion/") {
            pack_args.push("--preserve-workspaces");
        }
    }

    pack_args.push("--filename");
    pack_args.push(pack_path.as_str());

    run_prepared_command(
        make_yarn_command(zpm_switch::ReleaseLine::Berry).await?,
        folder_path,
        pack_args,
        [("YARN_ENABLE_INLINE_BUILDS", "1".to_string())],
        [],
    ).await?;

    let pack_tgz = pack_path
        .fs_read()?;

    Ok(pack_tgz)
}

async fn prepare_pnpm_project(folder_path: &Path, _params: &PrepareParams) -> Result<Vec<u8>, Error> {
    ScriptEnvironment::new()?
        .with_cwd(folder_path.clone())
        .run_exec("pnpm", vec!["install"])
        .await?
        .ok()?;

    let pack_result = ScriptEnvironment::new()?
        .with_cwd(folder_path.clone())
        .run_exec("pnpm", vec!["pack"])
        .await?
        .ok()?;

    let pack_file
        = String::from_utf8(pack_result.output().stdout.clone())?;

    let pack_tgz = folder_path
        .with_join_str(pack_file.trim())
        .fs_read()?;

    Ok(pack_tgz)
}

async fn prepare_yarn_zpm_project(folder_path: &Path, params: &PrepareParams) -> Result<Vec<u8>, Error> {
    let cwd_path = params.cwd.as_ref()
        .map(|cwd| folder_path.with_join_str(cwd))
        .unwrap_or(folder_path.clone());

    let archive_path = folder_path
        .with_join_str("archive.tgz");

    let mut pack_args = vec![];

    if let Some(workspace) = &params.workspace {
        pack_args.push("workspace");
        pack_args.push(workspace.as_str());
    }

    pack_args.push("pack");
    pack_args.push("--preserve-workspaces");
    pack_args.push("--install-if-needed");
    pack_args.push("--out");
    pack_args.push(archive_path.as_str());

    let current_exe
        = Path::current_exe()?;

    ScriptEnvironment::new()?
        .with_cwd(cwd_path.clone())

        .with_env_variable("YARNSW_DEFAULT", &format!("local:{}", current_exe.to_file_string()))
        .delete_env_variable("CACHE_CWD")
        .delete_env_variable("INIT_CWD")
        .delete_env_variable("NODE_OPTIONS")
        .delete_env_variable("PROJECT_CWD")
        .delete_env_variable("npm_config_user_agent")
        .delete_env_variable("npm_execpath")

        .run_exec("yarn", pack_args)
        .await?
        .ok()?;

    let pack_tgz = archive_path
        .fs_read()?;

    Ok(pack_tgz)
}
