use std::env;
use std::fs;
use std::io::{self, Read};
use std::path::Path;

fn main() {
    println!("cargo::rustc-check-cfg=cfg(target_vendor, values(\"browserpod\"))");

    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("ui_assets.rs");

    let zip_path = Path::new("src/daemon/server/ui.zip");

    println!("cargo::rerun-if-changed={}", zip_path.display());

    if !zip_path.exists() {
        // Generate an empty asset map when no UI zip is available
        fs::write(
            &dest_path,
            "pub fn get_ui_asset(_path: &str) -> Option<(&'static str, &'static [u8])> { None }\n",
        )
        .unwrap();
        return;
    }

    let zip_data = fs::read(zip_path).expect("Failed to read ui.zip");
    let entries = read_zip_entries(&zip_data).expect("Failed to parse ui.zip");

    let mut code = String::new();
    code.push_str("pub fn get_ui_asset(path: &str) -> Option<(&'static str, &'static [u8])> {\n");
    code.push_str("    match path {\n");

    for (name, content) in &entries {
        // Strip the leading "dist/" prefix
        let serve_path = name.strip_prefix("dist/").unwrap_or(name);
        if serve_path.is_empty() || serve_path.ends_with('/') {
            continue; // Skip directories
        }

        let mime = guess_mime(serve_path);
        code.push_str(&format!(
            "        {:?} => Some(({:?}, &{:?})),\n",
            serve_path, mime, content
        ));
    }

    code.push_str("        _ => None,\n");
    code.push_str("    }\n");
    code.push_str("}\n");

    fs::write(&dest_path, code).unwrap();
}

fn guess_mime(path: &str) -> &'static str {
    if path.ends_with(".html") {
        "text/html; charset=utf-8"
    } else if path.ends_with(".js") {
        "application/javascript; charset=utf-8"
    } else if path.ends_with(".css") {
        "text/css; charset=utf-8"
    } else if path.ends_with(".json") {
        "application/json"
    } else if path.ends_with(".svg") {
        "image/svg+xml"
    } else if path.ends_with(".png") {
        "image/png"
    } else if path.ends_with(".ico") {
        "image/x-icon"
    } else if path.ends_with(".woff2") {
        "font/woff2"
    } else if path.ends_with(".woff") {
        "font/woff"
    } else {
        "application/octet-stream"
    }
}

// Minimal zip reader — supports Store and Deflate methods only.
// We only need to read local file entries from a zip generated by the `zip` CLI.

fn read_zip_entries(data: &[u8]) -> io::Result<Vec<(String, Vec<u8>)>> {
    let mut entries = Vec::new();
    let mut pos = 0;

    while pos + 4 <= data.len() {
        let sig = u32::from_le_bytes([data[pos], data[pos + 1], data[pos + 2], data[pos + 3]]);
        if sig != 0x04034b50 {
            break; // Not a local file header
        }

        if pos + 30 > data.len() {
            break;
        }

        let method = u16::from_le_bytes([data[pos + 8], data[pos + 9]]);
        let compressed_size = u32::from_le_bytes([
            data[pos + 18],
            data[pos + 19],
            data[pos + 20],
            data[pos + 21],
        ]) as usize;
        let uncompressed_size = u32::from_le_bytes([
            data[pos + 22],
            data[pos + 23],
            data[pos + 24],
            data[pos + 25],
        ]) as usize;
        let name_len = u16::from_le_bytes([data[pos + 26], data[pos + 27]]) as usize;
        let extra_len = u16::from_le_bytes([data[pos + 28], data[pos + 29]]) as usize;

        let name_start = pos + 30;
        let name_end = name_start + name_len;
        let data_start = name_end + extra_len;
        let data_end = data_start + compressed_size;

        if data_end > data.len() {
            break;
        }

        let name = String::from_utf8_lossy(&data[name_start..name_end]).to_string();
        let raw = &data[data_start..data_end];

        let content = match method {
            0 => raw.to_vec(), // Store
            8 => {
                // Deflate
                let mut decoder = flate2::read::DeflateDecoder::new(raw);
                let mut buf = Vec::with_capacity(uncompressed_size);
                decoder.read_to_end(&mut buf)?;
                buf
            }
            _ => {
                return Err(io::Error::new(
                    io::ErrorKind::Unsupported,
                    format!("Unsupported zip method {} for {}", method, name),
                ));
            }
        };

        entries.push((name, content));
        pos = data_end;
    }

    Ok(entries)
}
