// This file is generated by `cargo run -p zpm --bin generate_daemon_types`.
// Do not edit by hand.

export type TaskSubscription = { name: string, args: Array<string>, };

export type SubscriptionScope = "none" | "targetOnly" | "fullTree";

export type DaemonRequestEnvelope = { requestId: number, request: DaemonRequest, };

export type DaemonRequest = { "type": "ping" } | { "type": "getMeta" } | { "type": "pushTasks", tasks: Array<TaskSubscription>, parentTaskId: string | null, workspace: string | null, outputSubscription: SubscriptionScope, statusSubscription: SubscriptionScope, 
/**
 * Context ID for task execution. Required for new tasks, inherited from parent for subtasks.
 */
contextId: string | null, } | { "type": "getTaskOutput", taskId: string, } | { "type": "stopTask", taskName: string, workspace: string | null, } | { "type": "listLongLivedTasks" } | { "type": "cancelContext", contextId: string, } | { "type": "getStats" } | { "type": "getTaskHistory" };

export type BufferedOutputLine = { line: string, stream: string, };

export type AttachedLongLivedTask = { taskId: string, startedAtMs: number, };

export type DaemonMeta = { version: string, };

export type LongLivedTaskStatus = "stopped" | { "running": { started_at_ms: number, process_id: number | null, } };

export type TaskEventState = { "type": "scheduled" } | { "type": "started", pid: number, } | { "type": "warm-up", pid: number, } | { "type": "live", pid: number, } | { "type": "completed" } | { "type": "failed", exit_code: number | null, signal: number | null, } | { "type": "cancelled" };

export type TaskEvent = { 
/**
 * Timestamp in milliseconds since the Unix epoch.
 */
date: number, 
/**
 * The contextual task ID (e.g. `workspace:taskname@context_id`).
 */
contextualTaskId: string, 
/**
 * The new task state.
 */
state: TaskEventState, };

export type LongLivedTaskInfo = { 
/**
 * The workspace name
 */
workspace: string, 
/**
 * The task name
 */
taskName: string, 
/**
 * Current status
 */
status: LongLivedTaskStatus, };

export type DaemonResponse = { "type": "pong" } | { "type": "meta", version: string, } | { "type": "tasksEnqueued", 
/**
 * The directly requested task IDs
 */
taskIds: string[], 
/**
 * Total number of dependency tasks (excluding target tasks)
 */
dependencyCount: number, 
/**
 * Long-lived tasks that we attached to (already running)
 */
attachedLongLived: Array<AttachedLongLivedTask>, } | { "type": "taskOutput", taskId: string, lines: Array<BufferedOutputLine>, } | { "type": "taskStopped", success: boolean, error: string | null, } | { "type": "longLivedTaskList", tasks: Array<LongLivedTaskInfo>, } | { "type": "contextCancelled", cancelledCount: number, } | { "type": "taskHistory", events: Array<TaskEvent>, } | { "type": "stats", 
/**
 * Number of entries in the tasks HashMap
 */
tasksCount: number, 
/**
 * Number of entries in the prepared BTreeMap
 */
preparedCount: number, 
/**
 * Number of entries in the subtasks HashMap
 */
subtasksCount: number, 
/**
 * Number of entries in the output_buffer HashMap
 */
outputBufferCount: number, 
/**
 * Number of entries in the closed_tasks queue
 */
closedTasksCount: number, } | { "type": "error", message: string, };

export type DaemonNotification = { "type": "taskOutputLine", taskId: string, line: string, stream: string, } | { "type": "taskStarted", taskId: string, } | { "type": "taskCompleted", taskId: string, exitCode: number, signal: number | null, } | { "type": "taskCancelled", taskId: string, } | { "type": "taskWarmUpComplete", taskId: string, };

export type DaemonMessage = { "kind": "response", requestId: number, response: DaemonResponse, } | { "kind": "notification", notification: DaemonNotification, };

