inputs:
  target:
    description: 'The target to build for'
    required: true
  profile:
    description: 'The profile to build with'
    required: true
    default: 'release-lto-nodebug'

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install Yarn Switch
      run: |
        bash install-script.sh

    - name: Install cross
      uses: taiki-e/install-action@a27ef18d36cfa66b0af3a360104621793b41c036 # v2.54.3
      with:
        tool: cross

    - name: Rust Cache
      uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 # v2.8.0

    - name: Add Rust Target
      run: rustup target add '${{inputs.target}}'

    - name: Compute the version
      id: version
      run: |
        git_sha=$GITHUB_SHA
        git_date=$(git show -s --format=%cd --date=format:'%Y%m%d' $GITHUB_SHA)

        zpm_version=$(cargo pkgid -p zpm | cut -d "#" -f2 | cut -d- -f1)
        INFRA_VERSION=$zpm_version-git.${git_date}.hash-${git_sha}

        echo -e "INFRA_VERSION=$INFRA_VERSION" >> $GITHUB_ENV
        echo -e "INFRA_VERSION=$INFRA_VERSION" >> $GITHUB_OUTPUT

    - name: Build ${{steps.version.outputs.INFRA_VERSION}}
      run: |
        cross build --verbose --profile=${{inputs.profile}} --target=${{matrix.target}}
        cp LICENSE.md target/${{matrix.target}}/${{inputs.profile}}/
